### ISSUE TITLE
Inquiry about Using Normalized Data for BayesPrism Deconvolution

### ISSUE THREAD

**Issue by linzhiheng2020** [Danko-Lab/BayesPrism#102]
Dear Author,

I hope this message finds you well. I have been working with the BayesPrism package for bulk RNA-seq deconvolution, and I have a few questions that I was hoping you might clarify.

Our input bulk RNA-seq matrix is already normalized (unfortunately, we have lost access to the raw count data). In this scenario, is it still appropriate to use BayesPrism for deconvolution, or is raw count data required for accurate results?

Given that our data is normalized, would further processing, such as scaling the entire matrix to a 0-1 range, be necessary or recommended before running BayesPrism?

Thank you very much for your time and assistance. I greatly appreciate any guidance you can provide on these points.

Best regards,
Zhiheng

**Comment by tinyi** [comment]
Dear Zhiheng,

Thank you for your interest in our method.

Yes. Our method also works for bulk RNA-seq normalized by linearly scaling
the data, such as RPM, RPKM and TPM, although raw count is the most
preferred input. Log transformation should be avoided.

Please do not use data scaled between 0-1, but should be scaled to a range
representing a typical total library size of bulk RNA-seq.

Best,

Tinyi

**Comment by linzhiheng2020** [comment]
Dear Tinyi,

I hope you're doing well. I wanted to sincerely thank you for your previous response — your guidance has been incredibly helpful as we continue our work with BayesPrism. We truly appreciate your time and expertise.

I have a follow-up question regarding normalized matrices that may contain negative values. In such cases, what would be the best approach to handle this? Should we adjust the matrix, and if so, what would be the recommended range for scaling? Additionally, if you happen to have any example code or specific suggestions for this adjustment, that would be greatly appreciated.

Once again, thank you very much for your support. Your assistance has been invaluable in advancing our analysis.

Best regards,
Zhiheng

**Comment by tinyi** [comment]
Hi Zhiheng,

Typically normalized bulk data should not contain negative values. The
scenario that may result in negative values can be the expression matrix is
z-scored, in which case it is typically not possible to transform it back
to the count scale, unless you know the mean and sd of each gene before
z-scoring, in which case you can apply z-score*sd+mean to transform it
back.

Best,

Tinyi

**Comment by linzhiheng2020** [comment]
Dear Tinyi,

Thank you so much for your invaluable guidance! Your advice on handling normalized matrices has been incredibly helpful, and I truly appreciate your expertise.

I hope to reach out again in the future if I encounter any further questions. Your support means a lot to us!

Best regards,
Zhiheng

**Comment by tinyi** [comment]
You are welcome, Zhiheng.
