### ISSUE TITLE
Documentation Error in cleanup.genes

### ISSUE THREAD

**Issue by aElia13** [Danko-Lab/BayesPrism#106]
Hello,

I think I detected an error in the documentation for the cleanup.genes function, specifically in:
https://github.com/Danko-Lab/BayesPrism/blob/6928e54d4beb022190633fc6fe9554ca88d39dae/BayesPrism/man/cleanup.genes.Rd#L21

- In the parameter "species", it is indicated that the character variable to denote if genes are human is "mm", and if mouse, "hs". I guess this should be indicated the other way around?

I hope to be of help.
Thanks for the package.

**Comment by tinyi** [comment]
Thank you very much for the catch. fixed now.
