### ISSUE TITLE
The proportion of cell population in input data

### ISSUE THREAD

**Issue by Chaosli98** [Danko-Lab/BayesPrism#13]
Hi, very useful tool! 
I wonder if the ratio of cell types in the input data is needed to maintain their true biological fraction, or just a certain number of cells is enough?

**Comment by tinyi** [comment]
Hi,

Thank you for your interest in our tool. BayesPrism does not take the cell
type fraction from the scRNA-seq reference into consideration. We only
recommend having a sufficient number of cells >20 or 50 for each cell type
when generating the reference.

Best,

Tinyi
