### ISSUE TITLE
Potential for scATAC-seq?

### ISSUE THREAD

**Issue by cnk113** [Danko-Lab/BayesPrism#16]
Hello,

I was wondering if this could potentially be used for scATAC-seq reference peaks to deconvolute bulk ATAC-seq expression?
Specifically I was wondering the constraints on the input matrix for such a way to have it work? I'm assuming I need to convert the peaks into an integer matrix.

Best,
Chang

**Comment by tinyi** [comment]
Hi Chang,

We haven’t benchmarked extensively for ATAC deconvolution, but I do not see
any reason why this cannot be generalized to ATAC - provided everything is
at the count scale which should naturally follow multinomial distribution.
We have tried to deconvolve enhancer RNAs measured by PRO-seq using
scATAC-seq, and it worked well. The input should be formulated as count
matrix over the peaks.

Best,

Tinyi
