### ISSUE TITLE
Issue with labelling of reference scRNA-seq data

### ISSUE THREAD

**Issue by Oreaster** [Danko-Lab/BayesPrism#24]
Hello,

there are some guidelines in the tutorial to annotate the reference scRNA-seq data, for example:
- "Define cell types as the cluster of cells having a sufficient number of significantly differentially expressed genes than other cell types, e.g., greater than 50 or even 100"
- "Define multiple cell states for cell types of significant heterogeneity, such as malignant cells, and of interest to deconvolve their transcription."

But I could not find any suggested workflow to annotate the reference data.

What would be the ideal way to generate the cell label and cell state annotations? Are there any suggested tools I could use?

Thank you and best regards

**Comment by tinyi** [comment]
Thank you for your interest in our tool.

We currently recommend users to use clustering methods developed for
scRNA-seq dataset, and annotate each biologically meaningful cluster.
Usually for tumor cells, we recommend refining it to subtypes (cell
states). We are planning to work on this problem in hope of providing a
statistically principled way to address this in the next version of
BaysePrism.

Best,

Tinyi

**Comment by Oreaster** [comment]
Thank you for you quick reply!

So a reasonable workflow could look like this:
UMAP -> cluster -> annotate cell types -> cluster cell types with high quantity of cells -> annotate cell states

Is that correct?

Thanks again and best regards

**Comment by tinyi** [comment]
We don’t usually cluster on umaps. Usually i do on the PC space.

You can subset cell types you believe to have high heterogeneity, e.g.
tumor cells, and recluster them to get finer clusters to use a cell states.

For details you may refer to tutorials of scanpy or Seurat.

**Comment by Oreaster** [comment]
I see, thank you very much for the explanations and suggestions :)

I have no further questions.
