### ISSUE TITLE
Cell states vs cell types

### ISSUE THREAD

**Issue by Benfeitas** [Danko-Lab/BayesPrism#28]
Hi, I'm having trouble understanding the cell states vs cell types. In my data I have identified cell types from multiple samples that come from 2 major groups, let's say disease and control. There is not substantial variability in disease vs control in different cell types, so I'm having trouble understanding how to specify the correct cell state in this case: when examining umap, they cluster by cell type and not by group.

If I specify cell states as group+sample, I will end up getting cell states being spread across cell types understandably:

    cell_state      endothelial      macrophages    pericyte    ....
    disease_1     300                 70                    0
    disease_2     199                 50                    80
    healthy_1     500                 130                  550

This means that I do not get substantial variability per sample (or source) to elicit distinct cell types. It also means I get the error `Error: one or more cell states belong to multiple cell types!`.

Likewise, in the example that you show in the tutorial you could easily have them spread across cell types. How would you recommend addressing this?

**Comment by tinyi** [comment]
Thank you for your interest in our tool.

If  there is not substantial variability in disease vs control in the cell
type of interest, you can simply label them as single cell type.
If there is variability, label the cell state as endothelial-disease_1 and
endothelial-disease_2, etc...
If the heterogeneity is huge, label them as distinct cell types (especially
when the disease-specific cell types are of interest
for downstream analysis).

Best,

Tinyi
