### ISSUE TITLE
Minimum number of cells per cell state 

### ISSUE THREAD

**Issue by sakinaamin** [Danko-Lab/BayesPrism#35]
Hi Tinyi,

While running new.prism() function, there is an error : "recommend to have sufficient number of cells in each cell state 
Error in new.prism(reference = sc.dat.filtered.pc, mixture = bk.dat, input.type = "count.matrix",  : 
  Error: one or more cell states belong to multiple cell types!"

I have 2 questions:
1. How many cells should be minimally per cell state?
2. Wouldn't cell states be part of multiple cell types?

**Comment by tinyi** [comment]
We recommend to have sufficient number of cells, a rule of thumb is 50 for
UMI-based scRNA-seq reference.

Each cell state, which is a finer-level subcluster, can only belong to one
cell type.
