### ISSUE TITLE
Error in if (any(which.row)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Tianqi-Ma** [Danko-Lab/BayesPrism#4]
Hi, BayesPrism team

I've played this package for a while and it performes very stable. But today I encountered an error like this:
```
recommend to have sufficient number of cells in each cell state
Number of outlier genes filtered from mixture = 44
Aligning reference and mixture...
Nornalizing reference...
Warning message:
In new.prism(reference = sc.dat.filtered.pc, mixture = bk.dat, input.type = "count.matrix",  :
  Warning: very few gene from reference and mixture match! Please double check your gene names.
Run Gibbs sampling...
Current time:  2022-07-19 02:02:40
Estimated time to complete:  2mins
Estimated finishing time:  2022-07-19 02:04:01
Start run...
R Version:  R version 4.1.2 (2021-11-01)

snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 50 CPUs.


Stopping cluster

Update the reference matrix ...
Error in if (any(which.row)) { : missing value where TRUE/FALSE needed
Calls: run.prism -> updateReference -> get.MLE.psi_mal -> norm.to.one
In addition: Warning message:
In searchCommandline(parallel, cpus = cpus, type = type, socketHosts = socketHosts,  :
  Unknown option on commandline: --file
Execution halted
```
It's kind of weird because the the query data (83 samples) is always the same in the past few succeed trials. The only difference is that the number of genes in it is reduced from 2000 to 901 like this
 
```
> dim(bk.dat)
[1]  83 901
```

Besides, if I subset some of the 83 samples and add part/all them up to make a artifical dataset like this.

```
data$testA1 = with(data, CR190516 + CR190517 + CR190518 + CR190522 + CR190523) ;
data$testA2 = with(data, CR190516 + CR190517 + CR190518 ) ;
data$testA3 = with(data, CR190518 + CR190522 + CR190523) ;
data$testA4 = with(data, CR190516 );
data$testA5 = with(data, CR190517 );
data$testA6 = with(data, CR190518 );
data$testA7 = with(data, CR190522 );
data$testA8 = with(data, CR190523 );
testSamples=colnames(data)[grepl("test", colnames(data))]
test = data[,testSamples]
rownames(test) = rownames(data) ;
testData=t(test) ;
bk.dat <- testData

```

No errors showed up.

Is the error coming from some of my samples?

**Comment by tinyi** [comment]
Hi Tianqi,

It seems a bit odd. If error is not reproducible, I would suspect it might
be a memory issue, in which case you may try using fewer threads. Also the
number of overlapping genes between your bulk data and reference is less
than 100, which may need to double check. If error persists, you may send
me your prism object, I am happy to help you troubleshoot.

Best,

Tinyi

**Comment by Tianqi-Ma** [comment]
Thank you for replying. I will try it later and let you know what's going on. 

BTW, I found the performance can be improved dramatically (at least in my case) when building query matrix using 975 genes from [https://www.deepcap.org/download](url). Perhaps you can have a test using this gene list and incooperate it into existed pipeline if it has a universal improvement (only for suggestion, of course).

**Comment by Tianqi-Ma** [comment]
I found this issue is some kind of sample-specific, but I didn't figure it out in detail. Please left an email address so that I can send you my prism object. Thank you very much for your help.

**Comment by tinyi** [comment]
Hi Tianqi,

Thank you for your suggestion. I took a brief look at those 975 genes. It
seems that those genes are used to define cancer types, rather than cell
types? Usually marker genes that define cell types would increase the
accuracy for all deconvolution algorithms. Also the size of genes 975 seems
to be slightly small IMO. I was curious about the setup of your problem and
the way performance was tested.

You may save your data as an rdata file and send it to ***@***.*** I
am happy to look into it.

Best,

Tinyi

**Comment by Tianqi-Ma** [comment]
Hi, Tinyi

Yes, in my case , I was trying to deconvolute tumor cells in blood sample. BTW, I can't see the email address.

**Comment by tinyi** [comment]
Looks like github automatically hides the email. Use tc532 at cornell.com

**Comment by Tianqi-Ma** [comment]
Cannot find tc532 at cornell.com. Is there a missing suffix?

**Comment by tinyi** [comment]
Hi Tianqi,

It turned out that the error was caused by have too few genes (N=63), and some bulk samples have zero expression over all selected genes. Unless there is a strong reason, I would recommend increase substantially increase number of genes. 

Best,

Tinyi

**Comment by Tianqi-Ma** [comment]
Ahhhhh, I was suspecting so as well. Anyway, thanks so much for your patience.

Hope you have a good day!
