### ISSUE TITLE
The problem of missing mouse genome files

### ISSUE THREAD

**Issue by ckqi22** [Danko-Lab/BayesPrism#41]
Hi，

When I assign 'mm' to the parameters 'species', in the step of filtering out the outlier genes, the function select.gene.type() will get an error. It might be due to lack of gene annotation file for mouse, like the "gencode.v22.broad.category.txt" file in the extdata folder. 

By the way, cleanup.genes() only support "MALAT1". If the species is mouse and change MALAT1 to Malat1, you will also get an error.

Thanks in advance !

**Comment by tinyi** [comment]
Thank you for your interest in our methods.

Yes. select.gene.type() only works for human genes, as noted in the
function description.

MALAT1 is a gene expressed to an extremely high level in human tumor
samples, so I designed the function to remove this gene for human samples.
I am not sure if it is also the case in mouse. Feel free to share your
advice on this.
