### ISSUE TITLE
cell states between map and phi_cellState do not match

### ISSUE THREAD

**Issue by seoyeonoh12** [Danko-Lab/BayesPrism#45]
Dear,

I am using BayesPrism to perform deconvolution by using two different levels of annotation (cell types and cell subtypes). 
However, I get this following error, while using only either annotation level works.

Error in validObject(.Object) : 
  invalid class “prism” object: cell states between map and phi_cellState do not match

The table of cell type labels and cell state labels looks like this. 
<img width="572" alt="Screenshot 2023-06-27 at 15 49 59" src="https://github.com/Danko-Lab/BayesPrism/assets/95966486/d3d6aca0-6c58-4c59-9be9-07bee63cffd6">

Thanks in advance.

Kind regards,
Seoyeon

**Comment by tinyi** [comment]
Hi Seoyeon,

I have not encountered this issue before. It is a bit difficult to
determine what is causing the error. Do you mind sending me a copy of your
data by dumping your input into rdata using save.image? Happy to
troubleshoot from there.

Best,

Tinyi

**Comment by seoyeonoh12** [comment]
The error has been solved! thank you :)

**Comment by tinyi** [comment]
thanks

**Comment by KaWingLee9** [comment]
> The error has been solved! thank you :)

I have met the same problem. Could you tell me how to solve it?

**Comment by AlexisFon** [comment]
Hi, I encountered the same problem.  @seoyeonoh12, would it be possible to share how you resolve it ?

**Comment by KaWingLee9** [comment]
@AlexisFon Maybe try to convert the cell type and cell state labels into factor?

**Comment by tinyi** [comment]
Hi all. cell.type.labels and cell.state.labels can be character or factor vectors. Happy to troubleshoot if you can share a test dataset that reproduce the error.
