### ISSUE TITLE
Expression contribution of different cell types to a gene

### ISSUE THREAD

**Issue by WuRAFY** [Danko-Lab/BayesPrism#52]
Hi, thanks for your tool. Here is some questions I have when using this tool.
I want to figure out which type of cell contribute most to expresion of a specific gene e.g. EGFR. I calculated the expression "contribution" by 
`EGFR expression of cell types × corresponding cell-type fractions`
Expression profile and cell-type fractions here are the results of BayesPrism. Then find out which type of cells contribute most to the gene expression. Does this make sense to you? Or do I need to do some normalization to the expression matrix of all cell types from same patient?
Thank you!

**Comment by tinyi** [comment]
Thank you for your question.

To compare across different bulk samples, one simple approach would be to
normalize the EGFR expression from the deconovolved cell type-specific
expression array Z of each bulk sample by the total reads of EGFR in each
sample. By doing so, we can get a fraction of reads of EGFR from each cell
type in each sample.

**Comment by WuRAFY** [comment]
Sorry that I do not understand your meaning "normalize Z by total reads". As far as I think, cell fraction should also be involved in the calculation. To compare fration of reads of EGFR from different cell types, Z of different cell types should be weighted by its cell fraction. Could you please explain your calculation in detail ? Thanks.

**Comment by tinyi** [comment]
Let's say a particular the Z of bulk sample is a G-by-K matrix, with G
denoting number of genes and K denoting number of cell types. Note that the
summation over K recovers the original G-by-1 raw count expression vector
X.

For a particular gene g, to get the expression contributed by cell type k,
one may simply compute Z_gk / X_g, which represents the fraction of reads
from cell type k for gene g.
