### ISSUE TITLE
Fail to install package

### ISSUE THREAD

**Issue by KaWingLee9** [Danko-Lab/BayesPrism#55]
I failed to install BayesPrism. Here are the error message and packages information.
Thank you.

> remotes::install_local('./BayesPrism.zip',force=TRUE)

* installing *source* package âBayesPrismâ ...
** using staged installation
** help
No man pages found in package  âBayesPrismâ
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import âgplots::lowessâ by âstats::lowessâ when loading âBayesPrismâ
Warning: replacing previous import âBiocParallel::registerâ by âNMF::registerâ when loading âBayesPrismâ
Error: package or namespace load failed for âBayesPrismâ in namespaceExport(ns, exports):
 undefined exports: rdirichlet, sample.Z.theta_n, sample.theta_n, sample.n, Rcgminu, logsumexp, transform.phi_t, compute.elbo, log.mle.gamma, log.mle.gamma.grad, log.posterior.gamma, log.posterior.gamma.grad, plot.cor.phi, plot.scRNA.outlier, plot.bulk.outlier, plot.bulk.vs.sc, select.gene.type, cleanup.genes, get.exp.stat, select.marker, new.prism, run.prism, run.prism.st, update.theta, get.exp, get.fraction, learn.embedding.nmf, learn.embedding
Error: loading failed
Execution halted
ERROR: loading failed
* removing â/home/lijiarong/miniconda3/envs/R/lib/R/library/BayesPrismâ
Warning message:
In i.p(...) :
  installation of package â/tmp/RtmpzmRdM2/remotes4a2ff71f65077/.â had non-zero exit status

> sessionInfo(c('snowfall', 'NMF', 'gplots', 'scran', 'BiocParallel'))
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/lijiarong/miniconda3/envs/R/lib/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
character(0)

other attached packages:
[1] snowfall_1.84-6.2   NMF_0.26            gplots_3.1.3
[4] scran_1.22.1        BiocParallel_1.28.3

loaded via a namespace (and not attached):
 [1] compiler_4.1.3  graphics_4.1.3  tools_4.1.3     utils_4.1.3
 [5] grDevices_4.1.3 remotes_2.4.2   stats_4.1.3     datasets_4.1.3
 [9] methods_4.1.3   base_4.1.3

**Comment by tinyi** [comment]
Hi. Can you try the following?

library("devtools");
install_github("Danko-Lab/BayesPrism/BayesPrism")

**Comment by KaWingLee9** [comment]
I make it. Thank your for your advice.
