### ISSUE TITLE
get.fraction function can not extract the deconvolution information for state

### ISSUE THREAD

**Issue by Lao-Tz** [Danko-Lab/BayesPrism#63]
```R
> theta_type <- get.fraction(bp = bp.res,
+                       which.theta = "final",
+                       state.or.type = "type")

> theta_state <- get.fraction(bp = bp.res,
+                            which.theta = "final",
+                            state.or.type = "state")

> all(theta_type == theta_state)
[1] TRUE

> cell.state.labels %>% unique %>% length
[1] 34

> cell.type.labels %>% unique %>%  length
[1] 7

> cell.type.labels %in% cell.state.labels %>% any
[1] FALSE
```
R version 4.3.1
BayesPrism version 2.1
system Ubuntu 20.04

**Comment by tinyi** [comment]
Hello. Cell state is only available for first Gibbs sampling. The second
function call will return cell type info. You should receive a warning when
you specify which.theta = "final" and state.or.type = "state" .

**Comment by Lao-Tz** [comment]
> ```r
> theta_state <- get.fraction(bp = bp.res,
> +                            which.theta = "final",
> +                            state.or.type = "state")
> ```

Either specify **first** or use this code extract
`theta <- bp.res@posterior.initial.cellState@theta`
