### ISSUE TITLE
Error in get.exp.stat function

### ISSUE THREAD

**Issue by fredust** [Danko-Lab/BayesPrism#7]
Hello, thank you for creating this great package.

I met an Error while running the `get.exp.stat ` function:
`Error: logical subscript contains NAs`

I checked the original code, I think the error might due to NA output while filtering out comparisons for cell states from the same cell type. 
`	#filter out comparisons for cell states from the same cell type
	pairs.celltype.first <- ct.to.cst[match(fit.up$pairs$first, ct.to.cst[,"cell.state"]),"cell.type"]
	pairs.celltype.second <- ct.to.cst[match(fit.up$pairs$second, ct.to.cst[,"cell.state"]),"cell.type"]`

and I made a small change.
I change the
`ct.to.cst <- unique(cbind(cell.type=cell.type.labels, cell.state=cell.state.labels))`
to
`ct.to.cst <- unique(cbind.data.frame(cell.type=cell.type.labels, cell.state=cell.state.labels))`

Then it worked well.

I'm not sure if this is a problem with my cell naming or a general problem.

Thank you very much.

**Comment by tinyi** [comment]
Thank you for your interest in our work.

I would be happy to help troubleshoot if you feel convenient sharing the input of the get.exp.stat function with me . You may send it to tc532@cornell.edu .

Best,

Tinyi

**Comment by fredust** [comment]
> Thank you for your interest in our work.
> 
> I would be happy to help troubleshoot if you feel convenient sharing the input of the get.exp.stat function with me . You may send it to [tc532@cornell.edu](mailto:tc532@cornell.edu) .
> 
> Best,
> 
> Tinyi

Hello, thank you for your reply. I finally figured out what the problem was, because I set cell.type.labels and cell.state.labels as factor. After I set them as character, then it worked well. 

Thank you very much
