### ISSUE TITLE
Issue with run.prism Function

### ISSUE THREAD

**Issue by Hananebh** [Danko-Lab/BayesPrism#73]
Dear BaysPrism Team,

I hope this message finds you well. I am currently using the BaysPrism tool for my research. Firstly, I want to express my gratitude for the excellent work you've done in developing this powerful tool.

I am writing to bring to your attention an issue I have encountered during the execution of the run.prism function. Unfortunately, the process does not seem to terminate, and there are no error messages provided. I have reviewed the documentation and community forums, but I couldn't find a solution to this particular problem.
Loading required package: snowfall
Loading required package: snow
Loading required package: NMF
Loading required package: pkgmaker
Loading required package: registry
Loading required package: rngtools
Loading required package: cluster
NMF - BioConductor layer [OK] | Shared memory capabilities [NO: bigmemory] | Cores 79/80
  To enable shared memory capabilities, try: install.extras('
NMF
')
Warning messages:
1: replacing previous import ‘gplots::lowess’ by ‘stats::lowess’ when loading ‘BayesPrism’ 
2: replacing previous import ‘BiocParallel::register’ by ‘NMF::register’ when loading ‘BayesPrism’

bp.res <- run.prism(prism = myPrism, n.cores=50)
Run Gibbs sampling... 
Current time:  2023-12-20 09:42:25 
Estimated time to complete:  11mins 
Estimated finishing time:  2023-12-20 09:53:11 
Start run... 
R Version:  R version 4.2.3 (2023-03-15) 

snowfall 1.84-6.3 initialized (using snow 0.4-4): parallel execution on 50 CPUs.

I have followed the instructions carefully, and the previous steps executed without any problems. However, when it comes to the run.prism step, the process does not complete.

I would greatly appreciate your assistance in resolving this issue. If there are any specific logs or additional information you need from my end, please let me know. I am eager to continue using BaysPrism for my analysis, and any help you can provide would be invaluable.

Thank you for your time and support.

Hanane

**Comment by pcantalupo** [comment]
@Hananebh how did you resolve this?  I'm running into the same problem with run.prism.  The process does not complete and no error is thrown.

**Comment by tinyi** [comment]
Dear users,

I was not quite sure what is causing this. One guess is that the number of cores requested exceeds the number of cores available. If the problem persists. Could you do sessionInfo(), and paste the results? Thanks.

Best,

Tinyi
