### ISSUE TITLE
reference single cell

### ISSUE THREAD

**Issue by youcef-benmohammed** [Danko-Lab/BayesPrism#80]
Hello,

I have multiple single cell datasets that come from different conditions I'm curious to know how to appropriately merge multiple single cell datasets to create an appropriate single cell reference atlas, does BayesPrism handle integrated data like Seurat or Harmony?

Best, 
Youcef

**Comment by tinyi** [comment]
Hi Yousef,

You may find answers in this post: https://github.com/Danko-Lab/BayesPrism/issues/56 .

Best,

Tinyi
