### ISSUE TITLE
Example about Computing z-scores of signature genes for Z of the cell type of interest.

### ISSUE THREAD

**Issue by 1667857557** [Danko-Lab/BayesPrism#85]
Hi, Dr.Chu

Thank you for your excellent work. Could you provide some examples and code related to the downstream analyses, specifically "Computing z-scores of signature genes for Z of the cell type of interest"? It would be very helpful for our work. Thanks in advance!

Best,
Yu-Feng Huang

**Comment by tinyi** [comment]
Hi Yu-Feng,

Thank you for your interest in our method.

Could you kindly let me know which figure(s) in our manuscript were related
to the z-score you were referring to? Many thanks.

Best,

Tinyi

**Comment by 1667857557** [comment]
Hi Tinyi,

The step titled 'Computing z-scores of signature genes for Z of the cell type of interest' was mentioned under the 'Downstream Analysis' section in the tutorial_deconvolution.html file you provided.

Best,
Yu-Feng Huang

**Comment by tinyi** [comment]
Hi Yu-Feng,

z score is simply  (z_i - mean(z)) / sd(z). you can use the scale function
in R to compute this.

Best,

Tinyi
