### ISSUE TITLE
Deconvolution Using BayesPrism for Tumor Subtypes

### ISSUE THREAD

**Issue by xianjieshen** [Danko-Lab/BayesPrism#88]
Dear BayesPrism authors,

I am delighted that you have developed such an interesting package. I am currently researching the relationships between tumor subtypes. I have annotated a large database (79 samples), including microenvironment, immune, and stromal cells. I have isolated epithelial cells and annotated tumor subgroups, resulting in six cell types. I now have two Seurat objects: one is overall, including epithelial and microenvironment, and the other is a Malignant Seurat object.

Can I ignore immune cells and directly use the malignant epithelial subtypes for deconvolution? I noticed your cell.type.state, but I don’t understand how to construct this information. How should "cell.state.labels" be built? I am quite confused about this part.

Additionally, I noticed that you identify the effect of malignant programs, exclude malignant cells, and use it to explain new factor decomposition, obtaining cell proportions of subtypes. I am very interested in this because it is precisely what I want to do. However, I don’t understand how to apply my prior knowledge in this context.

I have already annotated malignant cells and identified subgroups. I want to exclude immune cells and get the proportions of the subgroups I annotated. How can I achieve this using your method?

And I don’t understand the meaning of this code,

`#Not run
ebd.res.myEta <- learn.embedding(bp = bp.res,
eta_prior = my.eta, # A user supplied K-by-G matrix, at a raw count (non-log) scale.
                                   cycle = 50,
                                   compute.elbo = T) `

How should the eta_prior parameter be used and constructed?

Thank you very much for your help.

Best regards,

Jason

**Comment by xianjieshen** [comment]
"I have already resolved the issue with cell.state.labels. Now, regarding the prior knowledge eta_prior = my.eta, how should I construct it?" 

> Dear BayesPrism authors,
> 
> I am delighted that you have developed such an interesting package. I am currently researching the relationships between tumor subtypes. I have annotated a large database (79 samples), including microenvironment, immune, and stromal cells. I have isolated epithelial cells and annotated tumor subgroups, resulting in six cell types. I now have two Seurat objects: one is overall, including epithelial and microenvironment, and the other is a Malignant Seurat object.
> 
> Can I ignore immune cells and directly use the malignant epithelial subtypes for deconvolution? I noticed your cell.type.state, but I don’t understand how to construct this information. How should "cell.state.labels" be built? I am quite confused about this part.
> 
> Additionally, I noticed that you identify the effect of malignant programs, exclude malignant cells, and use it to explain new factor decomposition, obtaining cell proportions of subtypes. I am very interested in this because it is precisely what I want to do. However, I don’t understand how to apply my prior knowledge in this context.
> 
> I have already annotated malignant cells and identified subgroups. I want to exclude immune cells and get the proportions of the subgroups I annotated. How can I achieve this using your method?
> 
> And I don’t understand the meaning of this code,
> 
> `#Not run ebd.res.myEta <- learn.embedding(bp = bp.res, eta_prior = my.eta, # A user supplied K-by-G matrix, at a raw count (non-log) scale. cycle = 50, compute.elbo = T) `
> 
> How should the eta_prior parameter be used and constructed?
> 
> Thank you very much for your help.
> 
> Best regards,
> 
> Jason

"I have already resolved the issue with cell.state.labels. Now, regarding the prior knowledge eta_prior = my.eta, how should I construct it?"

**Comment by tinyi** [comment]
Hi Jason,

You may construct a K-by-G matrix, with K being the number of subtypes. You
may simply sum-up the reads of all cells from each subtype, and renormalize
them to sum-to-one (for each subtype).

Best,

Tinyi
