### ISSUE TITLE
Cell state co-occurrence analysis

### ISSUE THREAD

**Issue by ConDem94** [Danko-Lab/BayesPrism#99]
Hi,

Thank you for this amazing package. Is it possible to analyse the co-occurrence of variable cell states across cell types using the state theta values? Similar to various ecotype papers where they used CIBERSORTx for deconvolution and then correlation analysis, I was wondering if this is possible here.

Best wishes,
Constantinos

**Comment by tinyi** [comment]
Hi Constantinos,

Thank you for your interest in our method.

Yes. The cell type fraction inferred by BayesPrism should be automatically
compatible with all downstream analyses involving cell type fractions.

Best,

Tinyi
